import type {
    ActionStep,
    BgColorStep,
    InteractionsDocument,
    MoveStep,
    OpacityStep,
    RotateStep,
    ScaleStep,
    SizeStep,
    Target,
} from '@weblab/models';
import { EditorAttributes } from '@weblab/constants';

const IX_ATTR = EditorAttributes.DATA_WEBLAB_IX_ID;

function cssSelectorForTarget(target: Target, triggerSourceIxId: string | null): string | null {
    switch (target.kind) {
        case 'self':
            if (!triggerSourceIxId) return null;
            return `[${IX_ATTR}="${triggerSourceIxId}"]`;
        case 'class':
            if (!target.value) return null;
            return `.${target.value}`;
        case 'ix-id':
            if (!target.value) return null;
            return `[${IX_ATTR}="${target.value}"]`;
        // sibling/child resolve only at runtime — no static CSS selector.
        case 'sibling':
        case 'child':
        case 'parent':
        default:
            return null;
    }
}

interface AccumulatedDeclarations {
    transform: string[];
    opacity?: string;
    width?: string;
    height?: string;
    backgroundColor?: string;
}

function applyStepDeclarations(decl: AccumulatedDeclarations, step: ActionStep): void {
    const payload = step.payload;
    switch (payload.kind) {
        case 'move': {
            const m = payload;
            const tx = m.x ? `${m.x.value}${m.x.unit === 'none' ? 'px' : m.x.unit}` : '0px';
            const ty = m.y ? `${m.y.value}${m.y.unit === 'none' ? 'px' : m.y.unit}` : '0px';
            const tz = m.z ? `${m.z.value}${m.z.unit === 'none' ? 'px' : m.z.unit}` : '0px';
            decl.transform.push(`translate3d(${tx}, ${ty}, ${tz})`);
            return;
        }
        case 'scale': {
            const s = payload;
            const sx = s.x ?? 1;
            const sy = s.y ?? sx;
            decl.transform.push(`scale(${sx}, ${sy})`);
            return;
        }
        case 'rotate': {
            const r = payload;
            const unit = r.z.unit === 'none' ? 'deg' : r.z.unit;
            decl.transform.push(`rotate(${r.z.value}${unit})`);
            return;
        }
        case 'opacity': {
            const o = payload;
            decl.opacity = String(o.value);
            return;
        }
        case 'size': {
            const sz = payload;
            if (sz.width) {
                const unit = sz.width.unit === 'none' ? 'px' : sz.width.unit;
                decl.width = `${sz.width.value}${unit}`;
            }
            if (sz.height) {
                const unit = sz.height.unit === 'none' ? 'px' : sz.height.unit;
                decl.height = `${sz.height.value}${unit}`;
            }
            return;
        }
        case 'bg-color': {
            const b = payload;
            decl.backgroundColor = b.color;
            return;
        }
    }
}

function renderRule(selector: string, decl: AccumulatedDeclarations): string | null {
    const lines: string[] = [];
    if (decl.transform.length > 0) {
        lines.push(`    transform: ${decl.transform.join(' ')};`);
    }
    if (decl.opacity != null) {
        lines.push(`    opacity: ${decl.opacity};`);
    }
    if (decl.width) {
        lines.push(`    width: ${decl.width};`);
    }
    if (decl.height) {
        lines.push(`    height: ${decl.height};`);
    }
    if (decl.backgroundColor) {
        lines.push(`    background-color: ${decl.backgroundColor};`);
    }
    if (lines.length === 0) return null;
    return `${selector} {\n${lines.join('\n')}\n}`;
}

/**
 * Emit `interactions-initial.css` content. One rule per (selector, animation).
 * If two initial states share a selector but live in different animations,
 * they each get their own rule — declarations later in document order win
 * via normal CSS cascade.
 */
export function emitInitialCss(doc: InteractionsDocument): string {
    const rules: string[] = [];
    rules.push('/* generated by weblab — do not edit */');

    for (const ix of doc.interactions) {
        if (!ix.enabled) continue;
        for (const animation of ix.animations) {
            const initialSteps = animation.steps.filter((s) => s.isInitial);
            if (initialSteps.length === 0) continue;

            const target = animation.targetOverride ?? ix.target;
            const selector = cssSelectorForTarget(target, ix.trigger.sourceIxId);
            if (!selector) continue;

            const decl: AccumulatedDeclarations = { transform: [] };
            for (const step of initialSteps) {
                applyStepDeclarations(decl, step);
            }
            const rule = renderRule(selector, decl);
            if (rule) rules.push(rule);
        }
    }

    return rules.join('\n\n') + '\n';
}
