/**
 * Generator for the Next.js `middleware.ts` that enforces per-page password
 * protection on a published Weblab site.
 *
 * The generated middleware ships HTTP Basic Auth — the browser shows a native
 * password prompt, the middleware verifies against a PBKDF2 hash, and on
 * success the request is forwarded to the static page. Hashes are emitted
 * verbatim; no plaintext password is ever embedded.
 *
 * The generated file starts with the marker comment below. The publish
 * pipeline should refuse to overwrite a `middleware.ts` that lacks this marker
 * so user-authored middleware is never clobbered.
 */

export const ACCESS_MIDDLEWARE_MARKER = '@weblab-access-middleware';

export interface ProtectedPage {
    /** Route path, normalised to start with `/`. e.g. `/about`, `/blog/post`. */
    pagePath: string;
    /** `pbkdf2$<iterations>$<saltB64>$<hashB64>` (see `page-access/hash.ts`). */
    passwordHash: string;
}

const escapeForString = (value: string): string => JSON.stringify(value);

/**
 * Build the source for `middleware.ts`. Returns null when there are no
 * password-protected pages — callers should treat that as "remove middleware
 * if it was previously generated by us".
 */
export const generateAccessMiddleware = (pages: ProtectedPage[]): string | null => {
    if (pages.length === 0) {
        return null;
    }

    // Deduplicate + sort for stable output (avoids spurious diffs across publishes).
    const seen = new Map<string, string>();
    for (const page of pages) {
        if (page.pagePath && page.passwordHash) {
            seen.set(page.pagePath, page.passwordHash);
        }
    }
    if (seen.size === 0) {
        return null;
    }
    const entries = [...seen.entries()].sort(([a], [b]) => a.localeCompare(b));

    const protectedLines = entries
        .map(([path, hash]) => `    ${escapeForString(path)}: ${escapeForString(hash)},`)
        .join('\n');

    const matcherLines = entries.map(([path]) => `    ${escapeForString(path)},`).join('\n');

    return `/* ${ACCESS_MIDDLEWARE_MARKER} */
// Auto-generated by Weblab on publish. Do not edit manually — your changes
// will be overwritten the next time this site is published.

import { NextResponse, type NextRequest } from 'next/server';

const PROTECTED: Record<string, string> = {
${protectedLines}
};

async function verify(password: string, stored: string): Promise<boolean> {
    const parts = stored.split('$');
    if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false;
    const iterations = Number.parseInt(parts[1] ?? '', 10);
    if (!Number.isFinite(iterations) || iterations <= 0) return false;
    const salt = Uint8Array.from(atob(parts[2] ?? ''), (c) => c.charCodeAt(0));
    const expected = Uint8Array.from(atob(parts[3] ?? ''), (c) => c.charCodeAt(0));
    const enc = new TextEncoder();
    const keyMaterial = await crypto.subtle.importKey(
        'raw',
        enc.encode(password),
        { name: 'PBKDF2' },
        false,
        ['deriveBits'],
    );
    const bits = await crypto.subtle.deriveBits(
        { name: 'PBKDF2', salt, iterations, hash: 'SHA-256' },
        keyMaterial,
        expected.length * 8,
    );
    const actual = new Uint8Array(bits);
    if (actual.length !== expected.length) return false;
    let diff = 0;
    for (let i = 0; i < actual.length; i += 1) {
        diff |= (actual[i] ?? 0) ^ (expected[i] ?? 0);
    }
    return diff === 0;
}

export async function middleware(request: NextRequest) {
    const stored = PROTECTED[request.nextUrl.pathname];
    if (!stored) return NextResponse.next();
    const auth = request.headers.get('authorization');
    if (!auth?.startsWith('Basic ')) {
        return new Response('Password required', {
            status: 401,
            headers: { 'WWW-Authenticate': 'Basic realm="Protected"' },
        });
    }
    try {
        const decoded = atob(auth.slice(6));
        const colonIdx = decoded.indexOf(':');
        const password = colonIdx >= 0 ? decoded.slice(colonIdx + 1) : decoded;
        const ok = await verify(password, stored);
        if (!ok) {
            return new Response('Invalid password', {
                status: 401,
                headers: { 'WWW-Authenticate': 'Basic realm="Protected"' },
            });
        }
        return NextResponse.next();
    } catch {
        return new Response('Invalid authorization header', { status: 400 });
    }
}

export const config = {
    matcher: [
${matcherLines}
    ],
};
`;
};

/**
 * Decide whether a given `middleware.ts` source was authored by us. Used by
 * the publish hook to avoid overwriting user-authored middleware files.
 */
export const isWeblabGeneratedMiddleware = (source: string): boolean => {
    return source.includes(ACCESS_MIDDLEWARE_MARKER);
};
