/**
 * Prompt-facing mirror of the curated component registry that lives in
 * `component-registry/` at the repo root. The folder holds the real source +
 * design tokens; this file is the typed catalog injected into the AI system
 * prompt so the agent knows exactly which components it may use and how to
 * install them.
 *
 * Keep this in sync with `component-registry/manifest.json`. The manifest is
 * generated by `component-registry/scripts/fetch-components.mjs`; when you add
 * components there, mirror the new rows here (future: codegen this from the
 * manifest at build time).
 */

export type ComponentRegistryLib = 'shadcn' | 'watermelon';

export interface ComponentRegistryItem {
    /** Registry slug, e.g. "button". */
    name: string;
    lib: ComponentRegistryLib;
    /** Coarse grouping for prompt readability. */
    category: string;
    description: string;
    /** Exported symbol, e.g. "Button". */
    componentName: string;
    /** In-project import path once installed. */
    importPath: string;
    /** URL passed to `bunx --bun shadcn@latest add "<installUrl>"`. */
    installUrl: string;
}

export const COMPONENT_REGISTRY: ComponentRegistryItem[] = [
    // shadcn/ui (new-york) primitives
    {
        name: 'accordion',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Disclosure accordion',
        componentName: 'Accordion',
        importPath: '@/components/ui/accordion',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/accordion.json',
    },
    {
        name: 'avatar',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Avatar image with fallback',
        componentName: 'Avatar',
        importPath: '@/components/ui/avatar',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/avatar.json',
    },
    {
        name: 'badge',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Status / tag badge',
        componentName: 'Badge',
        importPath: '@/components/ui/badge',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/badge.json',
    },
    {
        name: 'button',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Button with variant + size system',
        componentName: 'Button',
        importPath: '@/components/ui/button',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/button.json',
    },
    {
        name: 'card',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Surface container: Card, Header, Title, Content, Footer',
        componentName: 'Card',
        importPath: '@/components/ui/card',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/card.json',
    },
    {
        name: 'checkbox',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Checkbox',
        componentName: 'Checkbox',
        importPath: '@/components/ui/checkbox',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/checkbox.json',
    },
    {
        name: 'dialog',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Modal dialog',
        componentName: 'Dialog',
        importPath: '@/components/ui/dialog',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/dialog.json',
    },
    {
        name: 'input',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Text input',
        componentName: 'Input',
        importPath: '@/components/ui/input',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/input.json',
    },
    {
        name: 'label',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Form label',
        componentName: 'Label',
        importPath: '@/components/ui/label',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/label.json',
    },
    {
        name: 'select',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Select dropdown',
        componentName: 'Select',
        importPath: '@/components/ui/select',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/select.json',
    },
    {
        name: 'separator',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Hairline divider',
        componentName: 'Separator',
        importPath: '@/components/ui/separator',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/separator.json',
    },
    {
        name: 'skeleton',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Loading skeleton',
        componentName: 'Skeleton',
        importPath: '@/components/ui/skeleton',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/skeleton.json',
    },
    {
        name: 'switch',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Toggle switch',
        componentName: 'Switch',
        importPath: '@/components/ui/switch',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/switch.json',
    },
    {
        name: 'tabs',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Tabbed sections',
        componentName: 'Tabs',
        importPath: '@/components/ui/tabs',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/tabs.json',
    },
    {
        name: 'textarea',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Multi-line text input',
        componentName: 'Textarea',
        importPath: '@/components/ui/textarea',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/textarea.json',
    },
    {
        name: 'tooltip',
        lib: 'shadcn',
        category: 'primitive',
        description: 'Hover tooltip',
        componentName: 'Tooltip',
        importPath: '@/components/ui/tooltip',
        installUrl: 'https://ui.shadcn.com/r/styles/new-york/tooltip.json',
    },
    // Watermelon UI extras
    {
        name: 'alert',
        lib: 'watermelon',
        category: 'feedback',
        description: 'Inline alert callout',
        componentName: 'Alert',
        importPath: '@/components/watermelon-ui/alert',
        installUrl: 'https://registry.watermelon.sh/alert.json',
    },
    {
        name: 'animated-accordion',
        lib: 'watermelon',
        category: 'motion',
        description: 'Accordion with spring open/close',
        componentName: 'AnimatedAccordion',
        importPath: '@/components/watermelon-ui/animated-accordion',
        installUrl: 'https://registry.watermelon.sh/animated-accordion.json',
    },
    {
        name: 'badge',
        lib: 'watermelon',
        category: 'primitive',
        description: 'Watermelon badge variant',
        componentName: 'Badge',
        importPath: '@/components/watermelon-ui/badge',
        installUrl: 'https://registry.watermelon.sh/badge.json',
    },
    {
        name: 'card',
        lib: 'watermelon',
        category: 'surface',
        description: 'Watermelon card variant',
        componentName: 'Card',
        importPath: '@/components/watermelon-ui/card',
        installUrl: 'https://registry.watermelon.sh/card.json',
    },
    {
        name: 'switch',
        lib: 'watermelon',
        category: 'primitive',
        description: 'Watermelon toggle variant',
        componentName: 'Switch',
        importPath: '@/components/watermelon-ui/switch',
        installUrl: 'https://registry.watermelon.sh/switch.json',
    },
];

/**
 * Compact summary of the design-token contract (full source:
 * `component-registry/theme/tokens.css`). These CSS variables ARE the palette —
 * the agent styles with `bg-background`, `text-foreground`, `border-border`,
 * `ring-ring`, etc., and never hardcodes a hex.
 */
export const WEBLAB_DESIGN_TOKENS_SUMMARY = [
    'Color + radius come ONLY from component-registry/theme/tokens.css (shadcn CSS-var contract):',
    '- Surfaces/text: --background, --foreground, --card(/-foreground), --popover(/-foreground), --muted(/-foreground)',
    '- Actions: --primary(/-foreground) = ink (near-black/near-white), --secondary, --accent (faint neutral hover)',
    '- The ONE whisper accent (muted teal) lives on --ring and --brand-accent only — focus/active/one CTA, never on text',
    '- Lines + state: --border, --input, --ring; --destructive(/-foreground) is muted',
    '- Radius: --radius (differentiate per component class; nested radius = inner + padding)',
    'Fonts come ONLY from component-registry/theme/fonts.md (Direction A: Geist; Direction B: Fraunces + Geist).',
].join('\n');

export const COMPONENT_REGISTRY_INSTALL_HINT =
    'Install a catalog component into the user project with its installUrl: bunx --bun shadcn@latest add "<installUrl>". Components land under @/components/ui (shadcn) or @/components/watermelon-ui (watermelon). Only install what the request needs.';
