export type ShadcnBlockCategory =
    | 'cta'
    | 'logos'
    | 'company'
    | 'content'
    | 'commerce'
    | 'help'
    | 'analytics'
    | 'primitive';

export interface ShadcnBlockManifestItem {
    registryName: string;
    label: string;
    description: string;
    category: ShadcnBlockCategory;
    componentName: string;
    importPath: string;
    installed: boolean;
}

export const SHADCN_BLOCKS: ShadcnBlockManifestItem[] = [
    {
        registryName: 'cta34',
        label: 'Cta 34',
        description: 'Separator call to action',
        category: 'cta',
        componentName: 'Cta34',
        importPath: '@/components/cta34',
        installed: true,
    },
    {
        registryName: 'cta35',
        label: 'Cta 35',
        description: 'Left border accent call to action',
        category: 'cta',
        componentName: 'Cta35',
        importPath: '@/components/cta35',
        installed: true,
    },
    {
        registryName: 'cta36',
        label: 'Cta 36',
        description: 'Split inline call to action',
        category: 'cta',
        componentName: 'Cta36',
        importPath: '@/components/cta36',
        installed: true,
    },
    {
        registryName: 'cta37',
        label: 'Cta 37',
        description: 'Grid split bordered call to action',
        category: 'cta',
        componentName: 'Cta37',
        importPath: '@/components/cta37',
        installed: true,
    },
    {
        registryName: 'cta38',
        label: 'Cta 38',
        description: 'Dark inverted card call to action',
        category: 'cta',
        componentName: 'Cta38',
        importPath: '@/components/cta38',
        installed: true,
    },
    {
        registryName: 'cta39',
        label: 'Cta 39',
        description: 'Dashed border card call to action',
        category: 'cta',
        componentName: 'Cta39',
        importPath: '@/components/cta39',
        installed: true,
    },
    {
        registryName: 'logos18',
        label: 'Logos 18',
        description: 'Logo grid without headline',
        category: 'logos',
        componentName: 'Logos18',
        importPath: '@/components/logos18',
        installed: true,
    },
    {
        registryName: 'about3',
        label: 'About 3',
        description: 'Company profile with achievements',
        category: 'company',
        componentName: 'About3',
        importPath: '@/components/about3',
        installed: true,
    },
    {
        registryName: 'awards1',
        label: 'Awards 1',
        description: 'Awards and recognition section',
        category: 'company',
        componentName: 'Awards1',
        importPath: '@/components/awards1',
        installed: true,
    },
    {
        registryName: 'blog7',
        label: 'Blog 7',
        description: 'Blog card section',
        category: 'content',
        componentName: 'Blog7',
        importPath: '@/components/blog7',
        installed: true,
    },
    {
        registryName: 'blogpost1',
        label: 'Blogpost 1',
        description: 'Long-form blog post layout',
        category: 'content',
        componentName: 'Blogpost1',
        importPath: '@/components/blogpost1',
        installed: true,
    },
    {
        registryName: 'careers4',
        label: 'Careers 4',
        description: 'Careers and open roles section',
        category: 'company',
        componentName: 'Careers4',
        importPath: '@/components/careers4',
        installed: true,
    },
    {
        registryName: 'case-studies2',
        label: 'Case Studies 2',
        description: 'Case studies listing section',
        category: 'content',
        componentName: 'CaseStudies2',
        importPath: '@/components/case-studies2',
        installed: true,
    },
    {
        registryName: 'code-example1',
        label: 'Code Example 1',
        description: 'Interactive code example section',
        category: 'content',
        componentName: 'CodeExample1',
        importPath: '@/components/code-example1',
        installed: true,
    },
    {
        registryName: 'community1',
        label: 'Community 1',
        description: 'Community callout with social links',
        category: 'company',
        componentName: 'Community1',
        importPath: '@/components/community1',
        installed: true,
    },
    {
        registryName: 'compare7',
        label: 'Compare 7',
        description: 'Comparison table section',
        category: 'content',
        componentName: 'Compare7',
        importPath: '@/components/compare7',
        installed: true,
    },
    {
        registryName: 'compliance1',
        label: 'Compliance 1',
        description: 'Compliance and trust badges section',
        category: 'company',
        componentName: 'Compliance1',
        importPath: '@/components/compliance1',
        installed: true,
    },
    {
        registryName: 'download2',
        label: 'Download 2',
        description: 'Download app/device CTA section',
        category: 'cta',
        componentName: 'Download2',
        importPath: '@/components/download2',
        installed: true,
    },
    {
        registryName: 'experience1',
        label: 'Experience 1',
        description: 'Experience/resume timeline section',
        category: 'company',
        componentName: 'Experience1',
        importPath: '@/components/experience1',
        installed: true,
    },
    {
        registryName: 'project1',
        label: 'Project 1',
        description: 'Single project showcase',
        category: 'content',
        componentName: 'Project1',
        importPath: '@/components/project1',
        installed: true,
    },
    {
        registryName: 'projects5',
        label: 'Projects 5',
        description: 'Projects gallery section',
        category: 'content',
        componentName: 'Projects5',
        importPath: '@/components/projects5',
        installed: true,
    },
    {
        registryName: 'product-quick-view4',
        label: 'Product Quick View 4',
        description: 'Product quick view dialog',
        category: 'commerce',
        componentName: 'ProductQuickView4',
        importPath: '@/components/product-quick-view4',
        installed: true,
    },
    {
        registryName: 'help1',
        label: 'Help 1',
        description: 'Category cards help center',
        category: 'help',
        componentName: 'Help1',
        importPath: '@/components/help1',
        installed: true,
    },
    {
        registryName: 'chart-group1',
        label: 'Chart Group 1',
        description: 'Two charts side by side',
        category: 'analytics',
        componentName: 'ChartGroup1',
        importPath: '@/components/chart-group1',
        installed: true,
    },
    {
        registryName: 'leaderboard1',
        label: 'Leaderboard 1',
        description: 'Leaderboard with progress bars',
        category: 'analytics',
        componentName: 'Leaderboard1',
        importPath: '@/components/leaderboard1',
        installed: true,
    },
    {
        registryName: 'chart-card1',
        label: 'Chart Card 1',
        description: 'Area chart card',
        category: 'analytics',
        componentName: 'ChartCard1',
        importPath: '@/components/chart-card1',
        installed: true,
    },
    {
        registryName: 'chart-card3',
        label: 'Chart Card 3',
        description: 'Bar chart card',
        category: 'analytics',
        componentName: 'ChartCard3',
        importPath: '@/components/chart-card3',
        installed: true,
    },
    {
        registryName: 'stats-card1',
        label: 'Stats Card 1',
        description: 'Metric card with trend',
        category: 'analytics',
        componentName: 'StatsCard1',
        importPath: '@/components/stats-card1',
        installed: true,
    },
];

export const SHADCN_CORE_COMPONENTS: ShadcnBlockManifestItem[] = [
    {
        registryName: 'button',
        label: 'Button',
        description: 'shadcn/ui button primitive',
        category: 'primitive',
        componentName: 'Button',
        importPath: '@/components/ui/button',
        installed: true,
    },
    {
        registryName: 'card',
        label: 'Card',
        description: 'shadcn/ui card primitive',
        category: 'primitive',
        componentName: 'Card',
        importPath: '@/components/ui/card',
        installed: true,
    },
    {
        registryName: 'badge',
        label: 'Badge',
        description: 'shadcn/ui badge primitive',
        category: 'primitive',
        componentName: 'Badge',
        importPath: '@/components/ui/badge',
        installed: true,
    },
    {
        registryName: 'separator',
        label: 'Separator',
        description: 'shadcn/ui separator primitive',
        category: 'primitive',
        componentName: 'Separator',
        importPath: '@/components/ui/separator',
        installed: true,
    },
    {
        registryName: 'progress',
        label: 'Progress',
        description: 'shadcn/ui progress primitive',
        category: 'primitive',
        componentName: 'Progress',
        importPath: '@/components/ui/progress',
        installed: true,
    },
    {
        registryName: 'avatar',
        label: 'Avatar',
        description: 'shadcn/ui avatar primitive',
        category: 'primitive',
        componentName: 'Avatar',
        importPath: '@/components/ui/avatar',
        installed: true,
    },
];

export const SHADCN_AVAILABLE_REGISTRY_HINT =
    'The @shadcnblocks registry is available through bunx --bun shadcn@latest add @shadcnblocks/<name>. Prefer installed manifest items first; install additional public blocks only when they directly fit the user request.';
