/**
 * The stand-in that follows the pointer while an element is being dragged.
 *
 * Feedback used to be the element fading to 40% opacity in place, which says
 * "something is happening to this" but not "this is the thing you are moving,
 * and it is here now". A ghost says both, and it is what makes a reorder read as
 * picking something up rather than as toggling a state on it.
 *
 * **It is cloned into the dragged element's own document, not onto the shell's
 * chrome layer.** That is the decision everything else here follows from, and it
 * buys three things at once:
 *
 * 1. The app's stylesheets are in that document. A clone rendered in the shell
 *    would arrive unstyled and have to carry a hand-maintained list of every
 *    visual property worth copying — the reference implementation bakes
 *    twenty-one and still misses pseudo-elements and backgrounds.
 * 2. A frame is an iframe inside the canvas's scaled world, so a `position:
 *    fixed` node inside it is scaled by that same transform. The ghost tracks
 *    canvas zoom for nothing. Drawn in the shell it would need a counter-scale,
 *    and would have to be re-derived on every zoom tick.
 * 3. `surface.toLocal` already converts a screen point into that document's
 *    coordinates, which is exactly the space `left`/`top` are written in.
 *
 * What the clone still cannot inherit is its *parent*: it no longer sits in the
 * flex row it was laid out in, and selectors like `.card > .title` or
 * `:nth-child(2)` no longer match it. Those are what `BAKED` copies — a much
 * shorter list than "everything", because the cascade covers the rest.
 */
import { design } from "@airship/editor-tokens";
import type { Point } from "../canvas/space";
import { computedStyle } from "../realm";
import { DRAGGING_CLASS, GHOST_MARK } from "../styles/portable.css";
import { localRect, type Surface } from "../surface";

/**
 * Properties the cascade cannot supply once the element is out of its parent.
 *
 * Two kinds, and no more. **Inherited** values came down the old ancestor chain
 * and would otherwise be re-inherited from `<body>`, so text in the ghost would
 * silently change colour and size. **Layout context** is what the element's own
 * children are arranged by; the wrapper is a bare div and cannot stand in for a
 * flex or grid container.
 *
 * Deliberately longhands. `getPropertyValue("border")` returns nothing at all in
 * some engines and an unparseable shorthand in others, and a shorthand that
 * fails to parse takes its longhands down with it.
 */
const BAKED = [
  // Inherited from an ancestor chain the ghost no longer has.
  "color",
  "direction",
  "font-family",
  "font-size",
  "font-style",
  "font-variant",
  "font-weight",
  "letter-spacing",
  "line-height",
  "list-style-type",
  "text-align",
  "text-indent",
  "text-transform",
  "white-space",
  "word-spacing",
  // The element's own layout context, which a bare wrapper cannot provide.
  "align-items",
  "box-sizing",
  "display",
  "flex-direction",
  "flex-wrap",
  "gap",
  "grid-auto-flow",
  "grid-template-columns",
  "grid-template-rows",
  "justify-content",
  "overflow-x",
  "overflow-y",
  // Paint that may have come from a selector qualified by the old parent.
  "background-color",
  "background-image",
  "background-position",
  "background-repeat",
  "background-size",
  "border-bottom-color",
  "border-bottom-style",
  "border-bottom-width",
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius",
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-top-color",
  "border-top-style",
  "border-top-width",
  "box-shadow",
  "object-fit",
  "padding-bottom",
  "padding-left",
  "padding-right",
  "padding-top",
  "text-decoration-line",
] as const;

/**
 * Elements that cannot render outside their parent, whatever we style them.
 *
 * A `<tr>` in a `<div>` has no layout at all — the engine drops it to `display:
 * block` and the row collapses — and the same is true of every other element
 * whose box is generated by its container's formatting context. These get an
 * outlined placeholder instead, which is honest: it shows the size and position
 * of what is moving without pretending to be a picture of it.
 */
const NOT_PORTABLE = new Set([
  "CAPTION",
  "COL",
  "COLGROUP",
  "OPTGROUP",
  "OPTION",
  "TBODY",
  "TD",
  "TFOOT",
  "TH",
  "THEAD",
  "TR",
]);

/** Above anything the app is likely to have. Its own document, so no conflict. */
const GHOST_Z = "2147483647";

export class DragGhost {
  private surface: Surface | null = null;
  private wrap: HTMLElement | null = null;
  /** Where inside the element the pointer grabbed it, in surface px. */
  private grab: Point = { x: 0, y: 0 };

  /** Build the ghost over `node` and pin it under the grab point. */
  attach(node: Element, surface: Surface, grabScreen: Point): void {
    this.detach();
    if (!surface.isLive) {
      return;
    }
    const rect = localRect(node);
    if (rect.width < 1 || rect.height < 1) {
      // Nothing to picture. The dragged node is still hidden and the drop
      // indicators still draw, so the gesture works — it just has no ghost.
      return;
    }
    const local = surface.toLocal(grabScreen);
    this.surface = surface;
    this.grab = { x: local.x - rect.left, y: local.y - rect.top };

    const wrap = surface.doc.createElement("div");
    wrap.setAttribute(GHOST_MARK, "");
    wrap.style.cssText = [
      "position:fixed",
      `left:${rect.left}px`,
      `top:${rect.top}px`,
      `width:${rect.width}px`,
      `height:${rect.height}px`,
      `z-index:${GHOST_Z}`,
      "margin:0",
      "padding:0",
      "border:0",
      "overflow:hidden",
      "opacity:.85",
      "transition:none",
      "pointer-events:none",
    ].join(";");
    wrap.append(
      NOT_PORTABLE.has(node.tagName)
        ? placeholder(surface)
        : portableClone(node, surface)
    );
    surface.doc.body.append(wrap);
    this.wrap = wrap;
  }

  /** Follow the pointer, keeping the grab point under it. */
  moveTo(screen: Point): void {
    if (!(this.wrap && this.surface?.isLive)) {
      return;
    }
    const local = this.surface.toLocal(screen);
    this.wrap.style.left = `${local.x - this.grab.x}px`;
    this.wrap.style.top = `${local.y - this.grab.y}px`;
  }

  detach(): void {
    this.wrap?.remove();
    this.wrap = null;
    this.surface = null;
  }
}

/**
 * A styled copy of the element, sized to fill the wrapper.
 *
 * The whole body is wrapped rather than guarded property by property. Cloning
 * a live subtree out of a host app's DOM touches enough of it — `cloneNode` on a
 * custom element runs its constructor, `getComputedStyle` on a detached realm
 * can throw during teardown — that the honest posture is "if anything about this
 * goes wrong, fall back to the outline". A ghost is feedback; it is never worth
 * a broken drag.
 */
function portableClone(node: Element, surface: Surface): HTMLElement {
  try {
    return bakedClone(node);
  } catch {
    return placeholder(surface);
  }
}

function bakedClone(node: Element): HTMLElement {
  const clone = node.cloneNode(true) as HTMLElement;
  // The original is hidden by this class, and `cloneNode` copies the attribute
  // along with everything else — so without this the ghost is invisible too.
  clone.classList.remove(DRAGGING_CLASS);
  neutralize(clone);

  const style = computedStyle(node);
  for (const property of BAKED) {
    const value = style.getPropertyValue(property);
    if (value) {
      clone.style.setProperty(property, value);
    }
  }

  // Everything that tied the element to its old position, undone. The wrapper
  // supplies the box; the clone fills it.
  clone.style.cssText += [
    ";position:static",
    "inset:auto",
    "margin:0",
    "float:none",
    "transform:none",
    "translate:none",
    "rotate:none",
    "scale:none",
    "visibility:visible",
    "opacity:1",
    "width:100%",
    "height:100%",
    "min-width:0",
    "min-height:0",
    "max-width:none",
    "max-height:none",
  ].join(";");
  return clone;
}

/** The fallback when a real copy cannot render: an outlined box its own size. */
function placeholder(surface: Surface): HTMLElement {
  const box = surface.doc.createElement("div");
  box.style.cssText = [
    "width:100%",
    "height:100%",
    `border:1px solid ${design.primary.primary}`,
    `background:${design.primary.bg}`,
  ].join(";");
  return box;
}

/**
 * Make the clone inert before it goes into the document.
 *
 * A drag ghost is a picture, but `cloneNode` produces a *live subtree* — and
 * inserting one has side effects that reach the app rather than the overlay:
 *
 * **Duplicate ids** are not cosmetic. `getElementById`, `<label for>` and every
 * `#id` selector resolve to the first match in document order, so a ghost
 * appended to `<body>` can capture references meant for the real element for as
 * long as the drag lasts.
 *
 * **A nested `<iframe>` loads a second document.** Dragging a card with an
 * embed in it would fire that embed's analytics again, re-initialise a payment
 * widget, or start a second video — for the duration of a gesture the user
 * thinks is moving one box. Dropping the source leaves the frame in the layout
 * as an empty box, which is the right trade: the ghost's job is to show shape
 * and position, not to be a working copy.
 *
 * **Autoplaying media** starts a second stream for the same reason.
 *
 * Cloned `<script>` elements are already handled by the platform — a clone
 * carries the "already started" flag and will not re-execute.
 */
function neutralize(root: HTMLElement): void {
  root.removeAttribute("id");
  for (const node of Array.from(root.querySelectorAll("[id]"))) {
    node.removeAttribute("id");
  }
  for (const frame of Array.from(
    root.querySelectorAll("iframe, object, embed")
  )) {
    frame.removeAttribute("src");
    frame.removeAttribute("srcdoc");
    frame.removeAttribute("data");
  }
  for (const media of Array.from(root.querySelectorAll("video, audio"))) {
    media.removeAttribute("autoplay");
    media.removeAttribute("src");
  }
}
