import { expect, test } from 'bun:test';
import { execFile, execFileSync } from 'node:child_process';
import { promisify } from 'node:util';
import { link, mkdir, mkdtemp, readFile, realpath, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';

import { createPrivateWorkingCopy, exportPrivateHandoff, grantLocalRoot, installDependencies, planPrivateHandoff, privateDependencyInstallIsCurrent, recordPrivateWrite, writeIfUnchanged } from './weblab-local.js';

const run = promisify(execFile);
const require = createRequire(import.meta.url);
const version = '7.0.0';
const integrity = 'sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==';
const tarball = `https://registry.npmjs.org/is-number/-/is-number-${version}.tgz`;
const manifest = JSON.stringify({
    name: 'migration-fixture', version: '1.0.0', private: true,
    dependencies: { 'is-number': version },
}) + '\n';

const fixtures = [
    {
        name: 'npm v3', file: 'package-lock.json',
        lock: JSON.stringify({
            name: 'migration-fixture', version: '1.0.0', lockfileVersion: 3,
            requires: true,
            packages: {
                '': { name: 'migration-fixture', version: '1.0.0', dependencies: { 'is-number': version } },
                'node_modules/is-number': { version, resolved: tarball, integrity },
            },
        }) + '\n',
        succeeds: true,
    },
    {
        name: 'Yarn v1', file: 'yarn.lock',
        lock: `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\nis-number@${version}:\n  version "${version}"\n  resolved "${tarball}"\n  integrity ${integrity}\n`,
        succeeds: true,
    },
    {
        name: 'Yarn v1 CRLF', file: 'yarn.lock',
        lock: `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\nis-number@${version}:\n  version "${version}"\n  resolved "${tarball}"\n  integrity ${integrity}\n`.replaceAll('\n', '\r\n'),
        succeeds: true,
    },
    {
        name: 'pnpm v9', file: 'pnpm-lock.yaml',
        lock: `lockfileVersion: '9.0'\n\nsettings:\n  autoInstallPeers: true\n  excludeLinksFromLockfile: false\n\nimporters:\n  .:\n    dependencies:\n      is-number:\n        specifier: ${version}\n        version: ${version}\n\npackages:\n  is-number@${version}:\n    resolution: {integrity: ${integrity}}\n\nsnapshots:\n  is-number@${version}: {}\n`,
        succeeds: true,
    },
    {
        name: 'unsupported npm v1', file: 'package-lock.json',
        lock: JSON.stringify({
            name: 'migration-fixture', version: '1.0.0', lockfileVersion: 1,
            requires: true,
            dependencies: { 'is-number': { version, resolved: tarball, integrity } },
        }) + '\n',
        succeeds: false,
    },
];

for (const fixture of fixtures) {
    test(`pinned Bun pm migrate: ${fixture.name}`, async () => {
        expect(process.versions.bun).toBe('1.3.10');
        const directory = await mkdtemp(join(tmpdir(), 'weblab-migrate-fixture-'));
        try {
            await writeFile(join(directory, 'package.json'), manifest);
            await writeFile(join(directory, fixture.file), fixture.lock);
            const result = await run(process.execPath, ['pm', 'migrate'], {
                cwd: directory,
                timeout: 15000,
                env: { PATH: process.env.PATH || '', HOME: directory, CI: '1' },
            }).then(() => ({ success: true }), (error) => ({ success: false, error }));
            expect(result.success).toBe(fixture.succeeds);
            expect(await readFile(join(directory, 'package.json'), 'utf8')).toBe(manifest);
            expect(await readFile(join(directory, fixture.file), 'utf8')).toBe(fixture.lock);
            if (fixture.succeeds) {
                const migrated = await readFile(join(directory, 'bun.lock'), 'utf8');
                expect(migrated).toContain('is-number');
                expect(migrated).toContain(version);
                expect(migrated).toContain(integrity);
                await expect(stat(join(directory, 'node_modules'))).rejects.toMatchObject({ code: 'ENOENT' });
            } else {
                await expect(stat(join(directory, 'bun.lock'))).rejects.toMatchObject({ code: 'ENOENT' });
            }
        } finally {
            await rm(directory, { recursive: true, force: true });
        }
    });
}

for (const fixture of fixtures.filter((item) => item.succeeds && item.name !== 'npm v3')) {
    test(`private ${fixture.name} install preserves the source lock`, async () => {
        const project = await mkdtemp(join(tmpdir(), 'weblab-foreign-source-'));
        const privateBase = await mkdtemp(join(tmpdir(), 'weblab-foreign-private-'));
        const git = (...args) => execFileSync('git', args, { cwd: project, encoding: 'utf8' });
        try {
            git('init', '-q');
            await writeFile(join(project, 'package.json'), manifest);
            await writeFile(join(project, fixture.file), fixture.lock);
            await writeFile(join(project, '.gitignore'), 'node_modules/\n');
            git('add', '.gitignore', 'package.json', fixture.file);
            git('-c', 'user.name=Test', '-c', 'user.email=test@example.invalid',
                'commit', '-qm', 'Initial');
            const source = await grantLocalRoot(project);
            const base = await realpath(privateBase);
            const copy = await createPrivateWorkingCopy(source, base);
            expect(await installDependencies(copy.rootPath, base)).toEqual({ success: true });
            expect(await privateDependencyInstallIsCurrent(copy.rootPath,
                join(base, copy.copyId), copy.copyId)).toBe(true);
            expect(await readFile(join(copy.rootPath, fixture.file), 'utf8')).toBe(fixture.lock);
            expect(await readFile(join(project, fixture.file), 'utf8')).toBe(fixture.lock);
            await expect(stat(join(copy.rootPath, 'bun.lock')))
                .rejects.toMatchObject({ code: 'ENOENT' });
        } finally {
            await rm(project, { recursive: true, force: true });
            await rm(privateBase, { recursive: true, force: true });
        }
    }, 20000);
}

test('uncertain install without private edits reopens a fresh copy and keeps the old one', async () => {
    const project = await mkdtemp(join(tmpdir(), 'weblab-reopen-source-'));
    const privateBase = await mkdtemp(join(tmpdir(), 'weblab-reopen-private-'));
    const git = (...args) => execFileSync('git', args, { cwd: project, encoding: 'utf8' });
    try {
        git('init', '-q');
        await writeFile(join(project, 'package.json'), manifest);
        await writeFile(join(project, fixtures[0].file), fixtures[0].lock);
        git('add', 'package.json', fixtures[0].file);
        git('-c', 'user.name=Test', '-c', 'user.email=test@example.invalid',
            'commit', '-qm', 'Initial');
        const source = await grantLocalRoot(project);
        const base = await realpath(privateBase);
        const original = await createPrivateWorkingCopy(source, base);
        await writeFile(join(base, original.copyId, 'dependency-install.json'),
            JSON.stringify({ version: 1, copyId: original.copyId, status: 'pending',
                childPid: process.pid }), { mode: 0o600 });
        const active = await createPrivateWorkingCopy(source, base);
        expect(active).toMatchObject({ rootPath: original.rootPath, reused: true });
        const modulePath = require.resolve('./weblab-local.js');
        delete require.cache[modulePath];
        const restarted = require(modulePath);
        await restarted.grantLocalRoot(project);
        const fresh = await restarted.createPrivateWorkingCopy(source, base);
        expect(fresh.reused).toBe(false);
        expect(fresh.priorCopyId).toBe(original.copyId);
        expect(fresh.rootPath).not.toBe(original.rootPath);
        expect((await stat(original.rootPath)).isDirectory()).toBe(true);
        expect(await readFile(join(project, fixtures[0].file), 'utf8')).toBe(fixtures[0].lock);
    } finally {
        await rm(project, { recursive: true, force: true });
        await rm(privateBase, { recursive: true, force: true });
    }
}, 20000);

test('private npm lock install leaves no generated lock and retries only its own interrupted lock', async () => {
    const project = await mkdtemp(join(tmpdir(), 'weblab-npm-source-'));
    const privateBase = await mkdtemp(join(tmpdir(), 'weblab-npm-private-'));
    const fixture = fixtures[0];
    const git = (cwd, ...args) => execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
    try {
        git(project, 'init', '-q');
        await writeFile(join(project, 'package.json'), manifest);
        await writeFile(join(project, fixture.file), fixture.lock);
        await writeFile(join(project, '.gitignore'), 'node_modules/\n');
        await writeFile(join(project, 'page.html'), '<h1>Before</h1>\n');
        git(project, 'add', '.gitignore', 'package.json', fixture.file, 'page.html');
        git(project, '-c', 'user.name=Test', '-c', 'user.email=test@example.invalid',
            'commit', '-qm', 'Initial');
        const source = await grantLocalRoot(project);
        const base = await realpath(privateBase);
        const copy = await createPrivateWorkingCopy(source, base);
        const container = join(base, copy.copyId);
        expect(await installDependencies(copy.rootPath, base)).toEqual({ success: true });
        expect(await privateDependencyInstallIsCurrent(copy.rootPath, container, copy.copyId)).toBe(true);
        expect(await readFile(join(copy.rootPath, 'package.json'), 'utf8')).toBe(manifest);
        expect(await readFile(join(copy.rootPath, fixture.file), 'utf8')).toBe(fixture.lock);
        expect(await readFile(join(project, fixture.file), 'utf8')).toBe(fixture.lock);
        await expect(stat(join(copy.rootPath, 'bun.lock'))).rejects.toMatchObject({ code: 'ENOENT' });
        expect(git(copy.rootPath, 'status', '--porcelain')).toBe('');
        await rm(join(copy.rootPath, 'node_modules', 'is-number'), { recursive: true, force: true });
        expect(await privateDependencyInstallIsCurrent(copy.rootPath, container, copy.copyId)).toBe(false);
        expect(await installDependencies(copy.rootPath, base)).toEqual({ success: true });
        const saved = await writeIfUnchanged(copy.rootPath, 'page.html', '<h1>After</h1>\n',
            createHash('sha256').update('<h1>Before</h1>\n').digest('hex'));
        expect(saved.success).toBe(true);
        await recordPrivateWrite(copy.rootPath, 'page.html', saved.hash, base);

        const manual = 'user lock\n';
        await writeFile(join(copy.rootPath, 'bun.lock'), manual);
        expect((await installDependencies(copy.rootPath, base)).error).toContain('Ambiguous lockfiles');
        expect(await readFile(join(copy.rootPath, 'bun.lock'), 'utf8')).toBe(manual);

        const lockPath = join(copy.rootPath, 'bun.lock');
        const recordPath = join(container, 'dependency-install.json');
        const markInterrupted = async (content) => {
            const tempName = 'generated-bun-lock-00000000-0000-4000-8000-000000000000.tmp';
            const stagedLock = join(container, tempName);
            await writeFile(stagedLock, content);
            const lockStat = await stat(stagedLock, { bigint: true });
            const previous = JSON.parse(await readFile(recordPath, 'utf8'));
            const generatedLockOwner = {
                tempName,
                hash: createHash('sha256').update(content).digest('hex'),
                dev: String(lockStat.dev), ino: String(lockStat.ino), size: String(lockStat.size),
                mtimeNs: String(lockStat.mtimeNs), birthtimeNs: String(lockStat.birthtimeNs),
            };
            await writeFile(recordPath, JSON.stringify({
                ...previous, status: 'pending', childPid: 99999999, generatedLockOwner,
            }));
            await link(stagedLock, lockPath);
        };
        await rm(lockPath);
        const staleTemp = join(container, 'install-abcdef');
        await mkdir(staleTemp);
        await writeFile(join(staleTemp, 'stale'), 'old private install');
        await markInterrupted('Weblab-generated lock interrupted before cleanup\n');
        const interrupted = JSON.parse(await readFile(recordPath, 'utf8'));
        await writeFile(recordPath, JSON.stringify({ ...interrupted, childPid: process.pid }));
        const reopened = await createPrivateWorkingCopy(source, base);
        expect(reopened).toMatchObject({ rootPath: copy.rootPath, reused: true });
        const handoff = await planPrivateHandoff(copy.rootPath, base);
        expect(handoff.unsupportedChanges).toEqual([]);
        const rescued = await exportPrivateHandoff(copy.rootPath, handoff.planToken, base);
        expect(await readFile(rescued.patchPath, 'utf8')).toContain('+<h1>After</h1>');
        expect((await installDependencies(copy.rootPath, base)).error)
            .toContain('may still be running');
        expect(await readFile(lockPath, 'utf8'))
            .toBe('Weblab-generated lock interrupted before cleanup\n');
        await writeFile(recordPath, JSON.stringify(interrupted));
        expect(await installDependencies(copy.rootPath, base)).toEqual({ success: true });
        await expect(stat(staleTemp)).rejects.toMatchObject({ code: 'ENOENT' });
        await expect(stat(lockPath)).rejects.toMatchObject({ code: 'ENOENT' });
        expect(await privateDependencyInstallIsCurrent(copy.rootPath, container, copy.copyId)).toBe(true);

        await markInterrupted('Weblab-generated lock interrupted again\n');
        await rm(lockPath);
        await writeFile(lockPath, 'user changed lock\n');
        expect((await installDependencies(copy.rootPath, base)).error).toContain('Generated bun.lock changed');
        expect(await readFile(lockPath, 'utf8')).toBe('user changed lock\n');
    } finally {
        await rm(project, { recursive: true, force: true });
        await rm(privateBase, { recursive: true, force: true });
    }
}, 60000);
