import type React from 'react';
import { useRef } from 'react';

import type { OGImage, PageMetadata, TitleMetadata } from '@weblab/models';
import { APP_NAME } from '@weblab/constants';
import { Button } from '@weblab/ui/button';
import { Icons } from '@weblab/ui/icons';
import { Input } from '@weblab/ui/input';
import { Separator } from '@weblab/ui/separator';
import { Textarea } from '@weblab/ui/textarea';

import type { FaviconRef } from './favicon';
import type { ImagePickerRef } from './image';
import { Favicon } from './favicon';
import ImagePicker from './image';

const getImageUrl = (images: OGImage | OGImage[] | undefined): string | undefined => {
    if (!images) {
        return undefined;
    }
    const image = Array.isArray(images) ? images[0] : images;
    if (typeof image === 'string') {
        return image;
    }
    if (image instanceof URL) {
        return image.toString();
    }
    return image?.url?.toString();
};

interface MetadataFormProps {
    title: string;
    titleObject: TitleMetadata;
    description: string;
    isDirty: boolean;
    projectUrl?: string;
    isSimpleTitle: boolean;
    disabled?: boolean;
    isSaving?: boolean;
    onTitleChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onTitleTemplateChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onTitleAbsoluteChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onDescriptionChange: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
    onImageSelect: (file: File) => void;
    onFaviconSelect?: (file: File) => void;
    onFaviconDarkSelect?: (file: File) => void;
    faviconUrl?: string;
    faviconDarkUrl?: string;
    onDiscard: () => void;
    onSave: () => void;
    showFavicon?: boolean;
    currentMetadata?: PageMetadata;
    defaultTitle?: string;
    defaultDescription?: string;
    isRoot?: boolean;
    leadingContent?: React.ReactNode;
    /** Slot rendered after the Open Graph block and before the sticky save bar.
     *  Used by the page settings drawer to host Schema markup + Access control
     *  without re-implementing the SEO/OG sections. */
    trailingContent?: React.ReactNode;
    // ── Open Graph overrides ─────────────────────────────────────────────────
    /** When true, save logic mirrors the SEO title into `metadata.openGraph.title`. */
    ogTitleSameAsSeo?: boolean;
    ogTitle?: string;
    onOgTitleChange?: (value: string) => void;
    onOgTitleSameAsSeoChange?: (value: boolean) => void;
    /** When true, save logic mirrors the SEO description into `metadata.openGraph.description`. */
    ogDescriptionSameAsSeo?: boolean;
    ogDescription?: string;
    onOgDescriptionChange?: (value: string) => void;
    onOgDescriptionSameAsSeoChange?: (value: boolean) => void;
}

const DEFAULT_TITLE = 'My New App';
const DEFAULT_DESCRIPTION = `Generated by ${APP_NAME}`;

export const MetadataForm = ({
    title,
    titleObject,
    description,
    isDirty,
    projectUrl,
    isSimpleTitle,
    disabled = false,
    isSaving = false,
    onTitleChange,
    onTitleTemplateChange,
    onTitleAbsoluteChange,
    onDescriptionChange,
    onImageSelect,
    onFaviconSelect,
    onFaviconDarkSelect,
    faviconUrl,
    faviconDarkUrl,
    onDiscard,
    onSave,
    showFavicon = false,
    currentMetadata,
    isRoot,
    leadingContent,
    trailingContent,
    ogTitleSameAsSeo,
    ogTitle,
    onOgTitleChange,
    onOgTitleSameAsSeoChange,
    ogDescriptionSameAsSeo,
    ogDescription,
    onOgDescriptionChange,
    onOgDescriptionSameAsSeoChange,
}: MetadataFormProps) => {
    const imagePickerRef = useRef<ImagePickerRef>(null);
    const faviconRef = useRef<FaviconRef>(null);
    const faviconDarkRef = useRef<FaviconRef>(null);

    const handleDiscard = () => {
        imagePickerRef.current?.reset();
        faviconRef.current?.reset();
        faviconDarkRef.current?.reset();
        onDiscard();
    };

    const renderTitle = () => {
        if (isSimpleTitle) {
            return (
                <div className="text-foreground-weblab grid grid-cols-2">
                    <div className="flex items-center">
                        <h2 className="text-regular font-medium">Title</h2>
                    </div>
                    <Input
                        placeholder="Title"
                        value={title}
                        className="text-miniPlus bg-background-secondary/75 text-foreground-primary border-background-secondary/75 col-span-1 break-words backdrop-blur-lg transition-all duration-150 ease-in-out"
                        onChange={onTitleChange}
                        disabled={disabled}
                    />
                </div>
            );
        } else {
            return (
                <div className="flex flex-col gap-4">
                    <h2 className="text-title3 text-foreground-weblab">Title Settings</h2>

                    <div className="text-foreground-weblab grid grid-cols-2">
                        <div className="flex items-center">
                            <h3 className="text-regular font-medium">Default Title</h3>
                        </div>
                        <Input
                            placeholder="Default title"
                            value={titleObject.default ?? ''}
                            className="text-miniPlus bg-background-secondary/75 text-foreground-primary border-background-secondary/75 col-span-1 break-words backdrop-blur-lg transition-all duration-150 ease-in-out"
                            onChange={onTitleChange}
                            disabled={disabled}
                        />
                    </div>
                    {!isRoot ? (
                        <div className="text-foreground-weblab grid grid-cols-2">
                            <div className="flex max-w-52 flex-col">
                                <h3 className="text-regular font-medium">Absolute Title</h3>
                                <p className="text-small">
                                    Ignores template from parents layout when set.
                                </p>
                            </div>
                            <Input
                                placeholder="Absolute title"
                                value={titleObject.absolute ?? ''}
                                className="text-miniPlus bg-background-secondary/75 text-foreground-primary border-background-secondary/75 col-span-1 break-words backdrop-blur-lg transition-all duration-150 ease-in-out"
                                onChange={onTitleAbsoluteChange}
                                disabled={disabled}
                            />
                        </div>
                    ) : (
                        <div className="text-foreground-weblab grid grid-cols-2">
                            <div className="flex max-w-52 flex-col">
                                <h3 className="text-regular font-medium">Title Template</h3>
                                <p className="text-small">
                                    Use %s as placeholder for child page titles (e.g., "%s | My
                                    Site")
                                </p>
                            </div>
                            <Input
                                placeholder="%s | My Site"
                                value={titleObject.template ?? ''}
                                className="text-miniPlus bg-background-secondary/75 text-foreground-primary border-background-secondary/75 col-span-1 break-words backdrop-blur-lg transition-all duration-150 ease-in-out"
                                onChange={onTitleTemplateChange}
                                disabled={disabled}
                            />
                        </div>
                    )}
                </div>
            );
        }
    };

    return (
        <div className="text-regular flex h-full flex-col">
            <div className="flex flex-1 flex-col gap-6 overflow-y-auto p-6 pb-24">
                {renderTitle()}

                <Separator />

                {leadingContent && (
                    <>
                        {leadingContent}
                        <Separator />
                    </>
                )}

                <div className="grid h-44 grid-cols-2">
                    <div className="text-foreground-weblab col-span-1 flex max-w-52 flex-col">
                        <h2 className="text-regular font-medium">Page Description</h2>
                        <p className="text-small">
                            This is the information that will show up on search engines below your
                            page title.
                        </p>
                    </div>

                    <Textarea
                        placeholder={DEFAULT_DESCRIPTION}
                        value={description}
                        className="text-miniPlus bg-background-secondary/75 text-foreground-primary border-background-secondary/75 col-span-1 break-words backdrop-blur-lg transition-all duration-150 ease-in-out"
                        onChange={onDescriptionChange}
                        disabled={disabled}
                        style={{
                            resize: 'none',
                            height: 'auto',
                            overflowY: 'auto',
                            overflowX: 'hidden',
                            overscrollBehavior: 'contain',
                            lineHeight: '1.5',
                        }}
                    />
                </div>

                <div className="flex flex-col gap-2">
                    <h2 className="text-regular text-foreground-weblab">Search Engine Preview</h2>
                    <div className="bg-background/50 flex flex-col gap-1.5 rounded-md border p-4">
                        <p className="text-miniPlus text-foreground-brand">{projectUrl}</p>
                        <h3 className="text-regular">{title || DEFAULT_TITLE}</h3>
                        <p className="text-regular text-foreground-tertiary line-clamp-2">
                            {description || DEFAULT_DESCRIPTION}
                        </p>
                    </div>
                </div>
                <Separator />
                <div className="flex flex-col gap-4">
                    <h2 className="text-title3">Open Graph</h2>
                    {onOgTitleChange && onOgTitleSameAsSeoChange && (
                        <div className="text-foreground-weblab flex flex-col gap-2">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="flex max-w-52 flex-col">
                                    <p className="text-regular font-medium">OG Title</p>
                                    <p className="text-small">
                                        Headline shown when this page is shared on social.
                                    </p>
                                </div>
                                <Input
                                    placeholder="Open Graph title"
                                    value={ogTitleSameAsSeo ? title : (ogTitle ?? '')}
                                    onChange={(event) => onOgTitleChange(event.target.value)}
                                    disabled={disabled || ogTitleSameAsSeo}
                                    className="text-miniPlus bg-background-secondary/75 text-foreground-primary border-background-secondary/75 col-span-1 break-words backdrop-blur-lg transition-all duration-150 ease-in-out"
                                />
                            </div>
                            <label className="text-mini text-foreground-secondary col-start-2 flex cursor-pointer items-center gap-2">
                                <input
                                    type="checkbox"
                                    className="accent-foreground-brand h-3.5 w-3.5"
                                    checked={Boolean(ogTitleSameAsSeo)}
                                    onChange={(event) =>
                                        onOgTitleSameAsSeoChange(event.target.checked)
                                    }
                                    disabled={disabled}
                                />
                                Same as SEO title tag
                            </label>
                        </div>
                    )}
                    {onOgDescriptionChange && onOgDescriptionSameAsSeoChange && (
                        <div className="text-foreground-weblab flex flex-col gap-2">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="flex max-w-52 flex-col">
                                    <p className="text-regular font-medium">OG Description</p>
                                    <p className="text-small">
                                        Short description shown under the OG title on social.
                                    </p>
                                </div>
                                <Textarea
                                    placeholder="Open Graph description"
                                    value={
                                        ogDescriptionSameAsSeo ? description : (ogDescription ?? '')
                                    }
                                    onChange={(event) => onOgDescriptionChange(event.target.value)}
                                    disabled={disabled || ogDescriptionSameAsSeo}
                                    className="text-miniPlus bg-background-secondary/75 text-foreground-primary border-background-secondary/75 col-span-1 min-h-20 break-words backdrop-blur-lg transition-all duration-150 ease-in-out"
                                    style={{ resize: 'none', lineHeight: '1.5' }}
                                />
                            </div>
                            <label className="text-mini text-foreground-secondary col-start-2 flex cursor-pointer items-center gap-2">
                                <input
                                    type="checkbox"
                                    className="accent-foreground-brand h-3.5 w-3.5"
                                    checked={Boolean(ogDescriptionSameAsSeo)}
                                    onChange={(event) =>
                                        onOgDescriptionSameAsSeoChange(event.target.checked)
                                    }
                                    disabled={disabled}
                                />
                                Same as SEO meta description
                            </label>
                        </div>
                    )}
                    <div className="text-foreground-weblab grid grid-cols-2">
                        <div className="flex max-w-52 flex-col">
                            <p className="text-regular font-medium">Social Preview Image</p>
                            <p className="text-small">Cropped to 1200 × 630 pixels.</p>
                        </div>
                        <div>
                            <ImagePicker
                                ref={imagePickerRef}
                                onImageSelect={onImageSelect}
                                url={getImageUrl(currentMetadata?.openGraph?.images)}
                            />
                        </div>
                    </div>
                    {showFavicon && (
                        <div className="grid grid-cols-2">
                            <div className="text-foreground-secondary max-w-52">
                                <p className="text-regular font-medium">Favicon</p>
                                <p className="text-small">
                                    The small icon shown in browser tabs and search results (64 × 64
                                    px). Add a separate dark-mode version if your icon needs more
                                    contrast on dark backgrounds.
                                </p>
                            </div>
                            <div className="flex flex-wrap gap-4">
                                <div className="flex flex-col items-center gap-1">
                                    <Favicon
                                        ref={faviconRef}
                                        onImageSelect={onFaviconSelect!}
                                        url={
                                            faviconUrl ??
                                            (typeof currentMetadata?.icons?.icon === 'string'
                                                ? currentMetadata.icons.icon
                                                : undefined)
                                        }
                                    />
                                    <span className="text-mini text-foreground-secondary">
                                        Light
                                    </span>
                                </div>
                                {onFaviconDarkSelect && (
                                    <div className="flex flex-col items-center gap-1">
                                        <Favicon
                                            ref={faviconDarkRef}
                                            onImageSelect={onFaviconDarkSelect}
                                            url={faviconDarkUrl}
                                        />
                                        <span className="text-mini text-foreground-secondary">
                                            Dark
                                        </span>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </div>
                {trailingContent && (
                    <>
                        <Separator />
                        {trailingContent}
                    </>
                )}
            </div>

            {/* Pinned buttons at the bottom */}
            <div
                className="bg-background border-border/50 sticky bottom-0 border-t p-6"
                style={{ borderTopWidth: '0.5px' }}
            >
                <div className="flex justify-end gap-4">
                    <Button
                        variant="outline"
                        className="bg-background border-border/50 flex items-center gap-2 border px-4 py-2"
                        type="button"
                        onClick={handleDiscard}
                        disabled={!isDirty || disabled}
                    >
                        <span>Discard changes</span>
                    </Button>
                    <Button
                        variant="secondary"
                        className="flex items-center gap-2 px-4 py-2"
                        type="button"
                        onClick={onSave}
                        disabled={!isDirty || disabled || isSaving}
                    >
                        {isSaving && <Icons.LoadingSpinner className="h-4 w-4 animate-spin" />}
                        <span>{isSaving ? 'Saving...' : 'Save changes'}</span>
                    </Button>
                </div>
            </div>
        </div>
    );
};
