export interface TypographyRowData {
    label: string;
    className: string;
    sizeDefault: number;
    weightDefault: number;
    leadingDefault: string;
    trackingDefault: number;
}

export const TYPOGRAPHY_ROWS: TypographyRowData[] = [
    {
        label: 'title1',
        className: 'text-title1',
        sizeDefault: 2.25,
        weightDefault: 400,
        leadingDefault: 'auto',
        trackingDefault: 0,
    },
    {
        label: 'title2',
        className: 'text-title2',
        sizeDefault: 1.5,
        weightDefault: 400,
        leadingDefault: 'normal',
        trackingDefault: 0,
    },
    {
        label: 'title3',
        className: 'text-title3',
        sizeDefault: 1.25,
        weightDefault: 400,
        leadingDefault: 'normal',
        trackingDefault: 0,
    },
    {
        label: 'large-plus',
        className: 'text-large-plus',
        sizeDefault: 1,
        weightDefault: 500,
        leadingDefault: '1.4rem',
        trackingDefault: 0.02,
    },
    {
        label: 'large',
        className: 'text-large',
        sizeDefault: 1,
        weightDefault: 400,
        leadingDefault: '1.4rem',
        trackingDefault: 0.02,
    },
    {
        label: 'regular-plus',
        className: 'text-regular-plus',
        sizeDefault: 0.9375,
        weightDefault: 500,
        leadingDefault: '1.4rem',
        trackingDefault: 0.02,
    },
    {
        label: 'regular',
        className: 'text-regular',
        sizeDefault: 0.9375,
        weightDefault: 300,
        leadingDefault: '1.4rem',
        trackingDefault: 0.02,
    },
    {
        label: 'small-plus',
        className: 'text-small-plus',
        sizeDefault: 0.8125,
        weightDefault: 500,
        leadingDefault: '1.3rem',
        trackingDefault: 0,
    },
    {
        label: 'small',
        className: 'text-small',
        sizeDefault: 0.8125,
        weightDefault: 300,
        leadingDefault: '1.3rem',
        trackingDefault: 0,
    },
    {
        label: 'mini-plus',
        className: 'text-mini-plus',
        sizeDefault: 0.75,
        weightDefault: 500,
        leadingDefault: 'normal',
        trackingDefault: 0.01,
    },
    {
        label: 'mini',
        className: 'text-mini',
        sizeDefault: 0.75,
        weightDefault: 400,
        leadingDefault: 'normal',
        trackingDefault: 0.01,
    },
    {
        label: 'micro-plus',
        className: 'text-micro-plus',
        sizeDefault: 0.6875,
        weightDefault: 500,
        leadingDefault: 'normal',
        trackingDefault: 0.005,
    },
    {
        label: 'micro',
        className: 'text-micro',
        sizeDefault: 0.6875,
        weightDefault: 400,
        leadingDefault: 'normal',
        trackingDefault: 0.005,
    },
];

export function typoVars(label: string) {
    return [
        `--font-size-${label}`,
        `--font-weight-${label}`,
        `--font-leading-${label}`,
        `--font-tracking-${label}`,
    ];
}

export interface ColorTokenData {
    name: string;
    cssVar: string;
    value: string;
    description: string;
    usage?: string;
}

export const SEMANTIC_TOKENS: ColorTokenData[] = [
    {
        name: 'background',
        cssVar: '--background',
        value: '20 14.3% 4.1%',
        description: 'Default page background. The base canvas the entire UI sits on.',
        usage: 'bg-background — body, app shell, root surfaces.',
    },
    {
        name: 'foreground',
        cssVar: '--foreground',
        value: '60 9.1% 97.8%',
        description: 'Default text color paired with --background.',
        usage: 'text-foreground — body copy, default headings.',
    },
    {
        name: 'primary',
        cssVar: '--primary',
        value: '60 9.1% 97.8%',
        description:
            'Brand-neutral high-emphasis surface. Used for solid primary buttons and the active progress bar fill.',
        usage: 'bg-primary, text-primary — primary Button, Progress fill.',
    },
    {
        name: 'primary-fg',
        cssVar: '--primary-foreground',
        value: '24 9.8% 10%',
        description: 'Foreground paired with --primary. Always legible on the primary surface.',
        usage: 'text-primary-foreground — text inside primary Button.',
    },
    {
        name: 'secondary',
        cssVar: '--secondary',
        value: '12 6.5% 15.1%',
        description: 'Low-emphasis surface for secondary actions and inactive tracks.',
        usage: 'bg-secondary — secondary Button, Slider track.',
    },
    {
        name: 'secondary-fg',
        cssVar: '--secondary-foreground',
        value: '60 9.1% 97.8%',
        description: 'Foreground paired with --secondary.',
        usage: 'text-secondary-foreground — text inside secondary Button.',
    },
    {
        name: 'muted',
        cssVar: '--muted',
        value: '12 6.5% 15.1%',
        description: 'Subtle background for de-emphasized regions and disabled-like fills.',
        usage: 'bg-muted — Tabs list bg, Skeleton, Kbd bg.',
    },
    {
        name: 'muted-fg',
        cssVar: '--muted-foreground',
        value: '24 5.4% 63.9%',
        description: 'Foreground for de-emphasized text: placeholders, captions, helper rows.',
        usage: 'text-muted-foreground — Input placeholder, Card description, Calendar outside days.',
    },
    {
        name: 'accent',
        cssVar: '--accent',
        value: '12 6.5% 15.1%',
        description: 'Hover/highlight fill for interactive list items and menu rows.',
        usage: 'bg-accent — DropdownMenu/Command highlighted item, NavigationMenu hover.',
    },
    {
        name: 'accent-fg',
        cssVar: '--accent-foreground',
        value: '60 9.1% 97.8%',
        description: 'Foreground paired with --accent on highlighted items.',
        usage: 'text-accent-foreground — text on hover in menus, Toggle pressed state.',
    },
    {
        name: 'destructive',
        cssVar: '--destructive',
        value: '0 72% 51%',
        description:
            'High-emphasis danger color for destructive actions, errors, and delete states.',
        usage: 'bg-destructive, text-destructive, border-destructive — destructive Button, error Alert, delete menu item.',
    },
    {
        name: 'destructive-fg',
        cssVar: '--destructive-foreground',
        value: '0 0% 100%',
        description: 'Foreground paired with --destructive.',
        usage: 'text-destructive-foreground — text on destructive Button.',
    },
    {
        name: 'border',
        cssVar: '--border',
        value: '0 0% 12%',
        description: 'Default 1px border across the system.',
        usage: 'border-border — Card, Separator, Input border, table rows.',
    },
    {
        name: 'border-hover',
        cssVar: '--border-hover',
        value: '0 0% 38%',
        description: 'Border color on hover for interactive bordered surfaces.',
        usage: 'hover:border-border-hover — Card hover, outlined Button hover.',
    },
    {
        name: 'border-active',
        cssVar: '--border-active',
        value: '0 0% 47%',
        description: 'Border color when an item is selected or pressed.',
        usage: 'border-border-active — selected list row, active tab.',
    },
    {
        name: 'input',
        cssVar: '--input',
        value: '12 6.5% 15.1%',
        description: 'Border + subtle fill for form inputs.',
        usage: 'border-input — Input, Textarea, Select trigger.',
    },
    {
        name: 'ring',
        cssVar: '--ring',
        value: '24 5.7% 82.9%',
        description: 'Focus ring color for keyboard navigation.',
        usage: 'focus-visible:ring-ring — every focusable control.',
    },
    {
        name: 'card',
        cssVar: '--card',
        value: '20 14.3% 4.1%',
        description: 'Background for Card surfaces. Slightly elevated compared to --background.',
        usage: 'bg-card — Card, surface tiles.',
    },
    {
        name: 'card-fg',
        cssVar: '--card-foreground',
        value: '60 9.1% 97.8%',
        description: 'Foreground paired with --card.',
        usage: 'text-card-foreground — text inside a Card.',
    },
    {
        name: 'popover',
        cssVar: '--popover',
        value: '20 14.3% 4.1%',
        description:
            'Floating surface background for menus, tooltips, popovers, and command palettes.',
        usage: 'bg-popover — DropdownMenu, Popover, Command, Select.',
    },
    {
        name: 'popover-fg',
        cssVar: '--popover-foreground',
        value: '60 9.1% 97.8%',
        description: 'Foreground paired with --popover.',
        usage: 'text-popover-foreground — text inside floating surfaces.',
    },
    // ── New semantic surfaces (Codex-aligned dark palette, 2026-05-23) ──────
    {
        name: 'modal',
        cssVar: '--modal',
        value: '#212121',
        description: 'Modal / dialog surface. Slightly raised above card.',
        usage: 'bg-modal — Dialog, Alert dialog, Sheet content.',
    },
    {
        name: 'modal-fg',
        cssVar: '--modal-foreground',
        value: '#ffffff',
        description: 'Foreground paired with --modal.',
        usage: 'text-modal-foreground — text inside modal/dialog.',
    },
    {
        name: 'background-modal-hover',
        cssVar: '--background-modal-hover',
        value: '#2e2e2e',
        description: 'Hover/selected row inside modal or popover.',
        usage: 'hover:bg-background-modal-hover — dialog list items.',
    },
    {
        name: 'background-popover-hover',
        cssVar: '--background-popover-hover',
        value: '#2e2e2e',
        description: 'Hover/selected item inside popover/dropdown.',
        usage: 'hover:bg-background-popover-hover — dropdown item.',
    },
    {
        name: 'background-tooltip',
        cssVar: '--background-tooltip',
        value: '#3f3f3f',
        description: 'Keyboard-shortcut tooltip pill (top of stack).',
        usage: 'bg-background-tooltip — Tooltip, Kbd shortcut pill.',
    },
    {
        name: 'foreground-tooltip',
        cssVar: '--foreground-tooltip',
        value: '#d6d6d6',
        description: 'Text on --background-tooltip.',
        usage: 'text-foreground-tooltip — tooltip label, kbd hint.',
    },
    {
        name: 'background-input',
        cssVar: '--background-input',
        value: '#1c1c1c',
        description: 'Form input fill — slightly inset feel.',
        usage: 'bg-background-input — Input, Textarea, Select.',
    },
    {
        name: 'background-chat-input',
        cssVar: '--background-chat-input',
        value: '#232323',
        description: 'Chat composer fill (no border).',
        usage: 'bg-background-chat-input — chat input box, prompt field.',
    },
    {
        name: 'background-selected',
        cssVar: '--background-selected',
        value: '#242424',
        description: 'Selected radio/checkbox card surface.',
        usage: 'data-state=checked:bg-background-selected — radio card.',
    },
    {
        name: 'background-sidebar',
        cssVar: '--background-sidebar',
        value: '#161616',
        description: 'Recessed sidebar bg (1 step below app backdrop).',
        usage: 'bg-background-sidebar — main sidebar container.',
    },
    {
        name: 'background-sidebar-active',
        cssVar: '--background-sidebar-active',
        value: '#222222',
        description: 'Sidebar active / hover / selected fill.',
        usage: 'data-active:bg-background-sidebar-active — sidebar row.',
    },
    {
        name: 'background-button-tertiary',
        cssVar: '--background-button-tertiary',
        value: '#1f1f1f',
        description: 'Tertiary button fill (subtle, no border).',
        usage: 'bg-background-button-tertiary — Button variant=tertiary.',
    },
    {
        name: 'background-dropdown-trigger',
        cssVar: '--background-dropdown-trigger',
        value: '#1f1f1f',
        description: 'Dropdown trigger fill (closed state).',
        usage: 'bg-background-dropdown-trigger — Select trigger, DropdownMenu trigger.',
    },
    {
        name: 'background-diff-added',
        cssVar: '--background-diff-added',
        value: '#193323',
        description: 'Added/inserted diff hunk surface.',
        usage: 'bg-background-diff-added — diff viewer added line.',
    },
    {
        name: 'background-diff-removed',
        cssVar: '--background-diff-removed',
        value: '#411d1a',
        description: 'Removed/deleted diff hunk surface.',
        usage: 'bg-background-diff-removed — diff viewer removed line.',
    },
    {
        name: 'foreground-diff-added',
        cssVar: '--foreground-diff-added',
        value: '#6fc57e',
        description: 'Green text/icon for added items.',
        usage: 'text-foreground-diff-added — +N tag, added file label.',
    },
    {
        name: 'foreground-diff-removed',
        cssVar: '--foreground-diff-removed',
        value: '#e35446',
        description: 'Red text/icon for removed items.',
        usage: 'text-foreground-diff-removed — -N tag, removed file label.',
    },
    {
        name: 'foreground-skill',
        cssVar: '--foreground-skill',
        value: '#ad7bf9',
        description: 'Purple accent for skill / agent / capability badges.',
        usage: 'text-foreground-skill — skill badge, agent tag.',
    },
    {
        name: 'foreground-code-orange',
        cssVar: '--foreground-code-orange',
        value: '#ff9335',
        description: 'Inline code highlight (warnings, keywords).',
        usage: 'text-foreground-code-orange — code token, syntax accent.',
    },
    {
        name: 'foreground-code-purple',
        cssVar: '--foreground-code-purple',
        value: '#bc69ff',
        description: 'Inline code highlight (types, identifiers).',
        usage: 'text-foreground-code-purple — code token, syntax accent.',
    },
    {
        name: 'foreground-placeholder',
        cssVar: '--foreground-placeholder',
        value: '#4d4d4d',
        description: 'Placeholder text for inputs / empty fields.',
        usage: 'placeholder:text-foreground-placeholder — Input placeholder.',
    },
    {
        name: 'border-card',
        cssVar: '--border-card',
        value: '#282828',
        description: 'Card outline (slightly stronger than --border).',
        usage: 'border-border-card — Card component outline.',
    },
    {
        name: 'border-input',
        cssVar: '--border-input',
        value: '#1c1c1c',
        description: 'Input outline (matches fill, near-invisible).',
        usage: 'border-border-input — Input default border.',
    },
    {
        name: 'border-search',
        cssVar: '--border-search',
        value: '#242424',
        description: 'Search input outline (more visible than regular input).',
        usage: 'border-border-search — search field.',
    },
    {
        name: 'border-secondary',
        cssVar: '--border-secondary',
        value: '#2c2c2c',
        description: 'Secondary button outline.',
        usage: 'border-border-secondary — secondary Button border.',
    },
    {
        name: 'border-popover',
        cssVar: '--border-popover',
        value: '#2d2d2d',
        description: 'Popover outline.',
        usage: 'border-border-popover — Popover, DropdownMenu border.',
    },
];

export const FOREGROUND_TOKENS: ColorTokenData[] = [
    {
        name: 'foreground-primary',
        cssVar: '--foreground-primary',
        value: '0 0% 100%',
        description: 'Highest-contrast text. Used for headings and key labels.',
        usage: 'text-foreground-primary — h1/h2, primary metrics.',
    },
    {
        name: 'foreground-secondary',
        cssVar: '--foreground-secondary',
        value: '0 0% 67%',
        description: 'Body text. The most common foreground in the product.',
        usage: 'text-foreground-secondary — paragraphs, default labels.',
    },
    {
        name: 'foreground-tertiary',
        cssVar: '--foreground-tertiary',
        value: '0 0% 57%',
        description: 'Supporting text: captions, helper text, timestamps.',
        usage: 'text-foreground-tertiary — file paths, "X minutes ago", placeholders.',
    },
    {
        name: 'foreground-quadranary',
        cssVar: '--foreground-quadranary',
        value: '0 0% 38%',
        description: 'Lowest-contrast readable text. Reserve for inactive labels.',
        usage: 'text-foreground-quadranary — disabled-ish metadata.',
    },
    {
        name: 'foreground-hover',
        cssVar: '--foreground-hover',
        value: '0 0% 78%',
        description: 'Foreground color on hover for tertiary/quadranary text.',
        usage: 'hover:text-foreground-hover — link rows, ghost button text.',
    },
    {
        name: 'foreground-active',
        cssVar: '--foreground-active',
        value: '0 0% 100%',
        description: 'Foreground when a control is selected or pressed.',
        usage: 'text-foreground-active — selected nav item, pressed Toggle.',
    },
    {
        name: 'foreground-disabled',
        cssVar: '--foreground-disabled',
        value: '0 0% 10%',
        description: 'Foreground inside disabled controls.',
        usage: 'disabled:text-foreground-disabled — disabled Button label.',
    },
    {
        name: 'foreground-brand',
        cssVar: '--foreground-brand',
        value: '205 100% 53%',
        description: 'Brand accent text. Use sparingly to highlight Weblab moments.',
        usage: 'text-foreground-brand — brand pills, marketing accents.',
    },
    {
        name: 'foreground-weblab',
        cssVar: '--foreground-weblab',
        value: '0 0% 67%',
        description: 'Foreground for the Weblab wordmark and brand strap.',
        usage: 'text-foreground-weblab — BrandWordmark text fill.',
    },
    {
        name: 'foreground-positive',
        cssVar: '--foreground-positive',
        value: '203 100% 78%',
        description: 'Positive/info text used on positive backgrounds.',
        usage: 'text-foreground-positive — "online" indicator, info pill.',
    },
    {
        name: 'foreground-success',
        cssVar: '--foreground-success',
        value: '206 100% 44%',
        description:
            'Success semantic foreground. Currently aliases the blue palette — flip with the design system when greens are introduced.',
        usage: 'text-foreground-success — "Added", "Verified", "Published".',
    },
    {
        name: 'foreground-warning',
        cssVar: '--foreground-warning',
        value: '206 100% 66%',
        description: 'Warning semantic foreground. Aliases blue today.',
        usage: 'text-foreground-warning — "Modified", "Attention", "Draft".',
    },
    {
        name: 'background-primary',
        cssVar: '--background-primary',
        value: '0 0% 10%',
        description: 'Slight lift over --background for primary panels.',
        usage: 'bg-background-primary — chat user bubble, active tab row.',
    },
    {
        name: 'background-secondary',
        cssVar: '--background-secondary',
        value: '0 0% 12%',
        description: 'Secondary panel surface. One step muted from --background.',
        usage: 'bg-background-secondary — tool-call rows, secondary cards.',
    },
    {
        name: 'background-tertiary',
        cssVar: '--background-tertiary',
        value: '0 0% 20%',
        description: 'Tertiary surface for deepest nested panels and chips.',
        usage: 'bg-background-tertiary — pill chips, hover-on-secondary fills.',
    },
    {
        name: 'background-hover',
        cssVar: '--background-hover',
        value: '0 0% 12%',
        description: 'Hover fill for ghost-style interactive surfaces.',
        usage: 'hover:bg-background-hover — list rows, sidebar items.',
    },
    {
        name: 'background-active',
        cssVar: '--background-active',
        value: '0 0% 20%',
        description: 'Pressed/active fill for ghost-style surfaces.',
        usage: 'active:bg-background-active, [data-state=open]:bg-background-active.',
    },
    {
        name: 'background-disabled',
        cssVar: '--background-disabled',
        value: '0 0% 10%',
        description: 'Disabled fill for surfaces.',
        usage: 'disabled:bg-background-disabled.',
    },
    {
        name: 'background-brand',
        cssVar: '--background-brand',
        value: '206 100% 28%',
        description: 'Saturated brand background. Use only for hero moments.',
        usage: 'bg-background-brand — featured CTA pill, promo banner.',
    },
    {
        name: 'background-brand-secondary',
        cssVar: '--background-brand-secondary',
        value: '206 100% 44%',
        description: 'Lighter brand variant for hover and secondary brand surfaces.',
        usage: 'hover:bg-background-brand-secondary.',
    },
    {
        name: 'background-positive',
        cssVar: '--background-positive',
        value: '208 100% 16%',
        description: 'Positive/info surface for tinted callouts.',
        usage: 'bg-background-positive — info Alert.',
    },
    {
        name: 'background-success',
        cssVar: '--background-success',
        value: '208 100% 16%',
        description: 'Success surface. Tinted background for "added" / "published" pills.',
        usage: 'bg-background-success/40 — success Badge fill.',
    },
    {
        name: 'background-success-secondary',
        cssVar: '--background-success-secondary',
        value: '206 100% 28%',
        description: 'Brighter success surface for hover.',
        usage: 'hover:bg-background-success-secondary.',
    },
    {
        name: 'background-warning',
        cssVar: '--background-warning',
        value: '206 100% 14%',
        description: 'Warning surface. Tinted background for "modified" / "pending" pills.',
        usage: 'bg-background-warning/40 — warning Badge fill.',
    },
    {
        name: 'background-warning-secondary',
        cssVar: '--background-warning-secondary',
        value: '206 100% 28%',
        description: 'Brighter warning surface for hover.',
        usage: 'hover:bg-background-warning-secondary.',
    },
    {
        name: 'background-toolbar-base',
        cssVar: '--background-toolbar-base',
        value: '0 0% 0%',
        description: 'Translucent base used to mix on top of canvas for floating toolbars.',
        usage: 'bg-background-toolbar-base — floating action bars.',
    },
    {
        name: 'background-weblab',
        cssVar: '--background-weblab',
        value: '0 0% 10%',
        description: 'Brand background paired with --foreground-weblab.',
        usage: 'bg-background-weblab — brand strap, marketing footer.',
    },
    {
        name: 'border-success',
        cssVar: '--border-success',
        value: '206 100% 44%',
        description: 'Border on success-tinted surfaces.',
        usage: 'border-border-success — success Badge outline.',
    },
    {
        name: 'border-warning',
        cssVar: '--border-warning',
        value: '206 100% 66%',
        description: 'Border on warning-tinted surfaces.',
        usage: 'border-border-warning — warning Badge outline.',
    },
];

export const CANVAS_EDITOR_TOKENS: ColorTokenData[] = [
    {
        name: 'background-canvas',
        cssVar: '--background-canvas',
        value: '0 0% 11%',
        description: 'Main viewport background where the user is rendering their site.',
        usage: 'bg-background-canvas — project editor canvas.',
    },
    {
        name: 'background-chrome',
        cssVar: '--background-chrome',
        value: '0 0% 7%',
        description: 'Full-height chrome: top nav, side panels.',
        usage: 'bg-background-chrome — editor shell.',
    },
    {
        name: 'background-bar',
        cssVar: '--background-bar',
        value: '0 0% 7%',
        description: 'Bottom toolbar bar background.',
        usage: 'bg-background-bar — bottom toolbar.',
    },
    {
        name: 'background-bar-active',
        cssVar: '--background-bar-active',
        value: '0 0% 18%',
        description: 'Pressed/active toolbar button background.',
        usage: 'data-active:bg-background-bar-active.',
    },
    {
        name: 'background-tab-strip',
        cssVar: '--background-tab-strip',
        value: '0 0% 15%',
        description: 'Container for the right-panel tab list.',
        usage: 'bg-background-tab-strip — right-panel tab strip.',
    },
    {
        name: 'background-tab-active',
        cssVar: '--background-tab-active',
        value: '0 0% 22%',
        description: 'Active tab fill in the tab strip.',
        usage: 'data-state=active:bg-background-tab-active.',
    },
    {
        name: 'border-canvas',
        cssVar: '--border-canvas',
        value: '0 0% 13%',
        description: '1px frame around the canvas viewport.',
        usage: 'border-border-canvas — canvas frame.',
    },
    {
        name: 'border-bar',
        cssVar: '--border-bar',
        value: '0 0% 14%',
        description: 'Border between the canvas and the bottom toolbar.',
        usage: 'border-border-bar — toolbar top edge.',
    },
    {
        name: 'border-tab-active',
        cssVar: '--border-tab-active',
        value: '0 0% 27%',
        description: 'Active tab outline.',
        usage: 'border-border-tab-active.',
    },
    {
        name: 'border-tab-divider',
        cssVar: '--border-tab-divider',
        value: '0 0% 24%',
        description: '1×14 vertical divider between tabs in the strip.',
        usage: 'bg-border-tab-divider — tab separator rule.',
    },
];

export const PALETTE = [
    {
        label: 'Blue / Amber',
        colors: [
            { name: '100', value: '206 100% 94%' },
            { name: '200', value: '206 100% 78%' },
            { name: '300', value: '206 100% 66%' },
            { name: '400', value: '206 100% 53%' },
            { name: '500', value: '206 100% 44%' },
            { name: '600', value: '206 100% 35%' },
            { name: '700', value: '206 100% 28%' },
            { name: '800', value: '206 100% 20%' },
            { name: '900', value: '206 100% 14%' },
        ],
    },
    {
        label: 'Gray',
        colors: [
            { name: '50', value: '0 0% 100%' },
            { name: '100', value: '0 0% 78%' },
            { name: '200', value: '0 0% 67%' },
            { name: '300', value: '0 0% 57%' },
            { name: '400', value: '0 0% 47%' },
            { name: '500', value: '0 0% 38%' },
            { name: '600', value: '0 0% 29%' },
            { name: '700', value: '0 0% 20%' },
            { name: '800', value: '0 0% 12%' },
            { name: '900', value: '0 0% 10%' },
        ],
    },
    {
        label: 'Red',
        colors: [
            { name: '100', value: '0 93% 94%' },
            { name: '200', value: '0 96% 89%' },
            { name: '300', value: '0 94% 82%' },
            { name: '400', value: '0 91% 71%' },
            { name: '500', value: '0 84% 60%' },
            { name: '600', value: '0 72% 51%' },
            { name: '700', value: '0 74% 42%' },
            { name: '800', value: '0 70% 35%' },
            { name: '900', value: '0 63% 31%' },
        ],
    },
];

export const RADIUS_PRESETS = [
    { label: 'sharp', value: 0.1 },
    { label: 'default', value: 1 },
    { label: 'soft', value: 1.6 },
    { label: 'pill', value: 3 },
];

export const RADII = [
    { name: 'xs', value: '0.25rem', tailwind: 'rounded-xs' },
    { name: 'sm', value: '0.5rem', tailwind: 'rounded-sm' },
    { name: 'md', value: '0.75rem', tailwind: 'rounded-md' },
    { name: 'lg', value: '1rem', tailwind: 'rounded-lg' },
    { name: 'xl', value: '1.25rem', tailwind: 'rounded-xl' },
    { name: '2xl', value: '1.5rem', tailwind: 'rounded-2xl' },
    { name: '3xl', value: '2rem', tailwind: 'rounded-3xl' },
    { name: 'full', value: '9999px', tailwind: 'rounded-full' },
];

export const SPACING_DATA = [1, 2, 3, 4, 6, 8, 10, 12, 16, 20, 24, 32];

export const WEBSITE_TYPOGRAPHY = [
    {
        label: 'heading-style-h1',
        className: 'heading-style-h1',
        size: '4xl → 7xl',
        note: 'Hero headline (one per page)',
    },
    {
        label: 'heading-style-h2',
        className: 'heading-style-h2',
        size: '4xl → 6xl',
        note: 'Major section headline',
    },
    {
        label: 'heading-style-h3',
        className: 'heading-style-h3',
        size: '3xl → 5xl',
        note: 'Section headline (medium)',
    },
    {
        label: 'heading-style-h4',
        className: 'heading-style-h4',
        size: '2xl → 4xl',
        note: 'Subsection / card title',
    },
    {
        label: 'heading-style-h5',
        className: 'heading-style-h5',
        size: 'xl',
        note: 'Small heading / large UI title',
    },
    {
        label: 'heading-style-h6',
        className: 'heading-style-h6',
        size: 'mini (uppercase)',
        note: 'Eyebrow / label',
    },
];

export const BODY_SCALE_RULES: Array<{
    use: string;
    useThis: string;
    avoid: string;
}> = [
    {
        use: 'Long-form body paragraph',
        useThis: 'text-regular (light) or text-large (default body)',
        avoid: 'text-base, text-sm',
    },
    {
        use: 'Lead paragraph under heading',
        useThis: 'text-large',
        avoid: 'text-lg, text-xl',
    },
    {
        use: 'Caption / metadata',
        useThis: 'text-mini (or text-mini-plus for emphasis)',
        avoid: 'text-xs, text-[11px]',
    },
    {
        use: 'UI label (button, tab, badge)',
        useThis: 'text-small / text-small-plus',
        avoid: 'text-sm font-medium',
    },
    {
        use: 'Tiny system text (status, counts)',
        useThis: 'text-micro / text-micro-plus',
        avoid: 'text-[10px]',
    },
    {
        use: 'Editor-side section title',
        useThis: 'text-title2 / text-title3',
        avoid: 'raw text-xl, text-2xl',
    },
];
